# generated by DipDup 8.5.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class CurateParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hDAO_amount: str
    issuer: str
    objkt_id: str
