# generated by DipDup 8.5.1

from __future__ import annotations

from typing import Any

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import RootModel


class Key(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str
    nat: str


class HenSplitSignerStorageItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: dict[str, Any]


class HenSplitSignerStorage(RootModel[list[HenSplitSignerStorageItem]]):
    root: list[HenSplitSignerStorageItem]
