spec_version: 3.0
package: teia_ecosystem_indexer

# Increase watchdog threshold to handle heavy historical transfer batches
advanced:
  watchdog_timeout: 60
  early_realtime: True
  merge_subscriptions: True

# database:
#   kind: sqlite
#   path: teia_ecosystem.sqlite3

database:
  kind: postgres
  database: teia_indexer
  host: ${POSTGRES_HOST:-localhost}
  port: ${POSTGRES_PORT:-5432}
  password: ${POSTGRES_PASS}
  user: ${POSTGRES_USER}
  immune_tables:
    - token_metadata

datasources:
  tzkt:
    kind: tezos.tzkt
    url: https://api.tzkt.io
    http:
      connection_timeout: 30
      retry_count: 5
  
  ipfs:
    kind: ipfs
    url: https://ipfs.io/ipfs

contracts:
  # The FA2 Token Registry (OBJKTs)
  hen_objkts:
    address: KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton
    typename: hen_objkts

  # V1 Minter & Market (Genesis)
  hen_minter_v1:
    address: KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9
    typename: hen_minter_v1

  # V2 Marketplace
  hen_market_v2:
    address: KT1HbQepzV1nVGg8QVznG7z4RcHseD5kwqBn
    typename: hen_market_v2

  # Teia Community Marketplace
  teia_market:
    address: KT1PHubm9HtyQEJ4BBpMTVomq6mhbfNZ9z5w
    typename: teia_market

  # HEN Identities (Subjkts)
  hen_subjkts:
    address: KT1My1wDZHDGweCrJnQJi3wcFaS67iksirvj
    typename: hen_subjkts

  # Split Contract Factory
  hen_split_factory:
    address: KT1DoyD6kr8yLK8mRBFusyKYJUk2ZxNHKP1N
    typename: hen_split_factory

  # Split Signer
  hen_split_signer:
    address: KT1BcLnWRziLDNJNRn3phAANKrEBiXhytsMY
    typename: hen_split_signer

indexes:
  # 1. Token Indexing (Mints)
  token_index:
    kind: tezos.operations
    datasources: 
      - tzkt
    first_level: 1365000
    contracts:
      - hen_objkts
    handlers:
      - callback: on_mint
        pattern:
          - destination: hen_objkts
            entrypoint: mint
      - callback: on_transfer
        pattern:
          - destination: hen_objkts
            entrypoint: transfer

  # 2. V1 Market Indexing
  market_v1_index:
    kind: tezos.operations
    datasources: 
      - tzkt
    first_level: 1365000
    contracts:
      - hen_minter_v1
    handlers:
      - callback: on_swap_v1
        pattern:
          - destination: hen_minter_v1
            entrypoint: swap
      - callback: on_collect_v1
        pattern:
          - destination: hen_minter_v1
            entrypoint: collect
      - callback: on_cancel_swap_v1
        pattern:
          - destination: hen_minter_v1
            entrypoint: cancel_swap

  # 3. V2 Market Indexing
  market_v2_index:
    kind: tezos.operations
    datasources: 
      - tzkt
    first_level: 1365000
    contracts:
      - hen_market_v2
    handlers:
      - callback: on_swap_v2
        pattern:
          - destination: hen_market_v2
            entrypoint: swap
      - callback: on_collect_v2
        pattern:
          - destination: hen_market_v2
            entrypoint: collect
      - callback: on_cancel_swap_v2
        pattern:
          - destination: hen_market_v2
            entrypoint: cancel_swap

  # 4. Teia Market Indexing
  market_teia_index:
    kind: tezos.operations
    datasources: 
      - tzkt
    first_level: 1365000
    contracts:
      - teia_market
    handlers:
      - callback: on_swap_teia
        pattern:
          - destination: teia_market
            entrypoint: swap
      - callback: on_collect_teia
        pattern:
          - destination: teia_market
            entrypoint: collect
      - callback: on_cancel_swap_teia
        pattern:
          - destination: teia_market
            entrypoint: cancel_swap

  # 5. Identities (Subjkts)
  subjkts_index:
    kind: tezos.operations
    datasources:
      - tzkt
    first_level: 1365000
    contracts:
      - hen_subjkts
    handlers:
      - callback: on_subjkt_register
        pattern:
          - destination: hen_subjkts
            entrypoint: registry
      - callback: on_subjkt_unregister
        pattern:
          - destination: hen_subjkts
            entrypoint: unregistry

  # 6. Split Contract Originations
  split_origination_index:
    kind: tezos.operations
    datasources:
      - tzkt
    first_level: 1365000
    contracts:
      - hen_split_factory
    handlers:
      - callback: on_split_origination
        pattern:
          - source: hen_split_factory
            type: origination

  # 7. Split Signatures
  split_sign_index:
    kind: tezos.operations
    datasources:
      - tzkt
    first_level: 1365000
    contracts:
      - hen_split_signer
    handlers:
      - callback: on_split_sign
        pattern:
          - destination: hen_split_signer
            entrypoint: sign

# Hook to fetch IPFS metadata asynchronously
hooks:
  fetch_metadata:
    callback: fetch_metadata
    atomic: False

# Background jobs
jobs:
  metadata_sync:
    hook: fetch_metadata
    interval: 300
