# generated by DipDup 8.5.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class SwapParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa2: str
    objkt_id: str
    objkt_amount: str
    xtz_per_objkt: str
    royalties: str
    creator: str
