# generated by DipDup 8.5.1

from __future__ import annotations

from typing import Any

from pydantic import BaseModel
from pydantic import ConfigDict


class Swaps(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    issuer: str
    fa2: str
    objkt_id: str
    objkt_amount: str
    xtz_per_objkt: str
    royalties: str
    creator: str


class TeiaMarketStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowed_fa2s: dict[str, dict[str, Any]]
    collects_paused: bool
    counter: str
    fee: str
    fee_recipient: str
    manager: str
    metadata: dict[str, str]
    proposed_manager: str | None = None
    swaps: dict[str, Swaps]
    swaps_paused: bool
