# generated by DipDup 8.5.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class Swaps(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    creator: str
    issuer: str
    objkt_amount: str
    objkt_id: str
    royalties: str
    xtz_per_objkt: str


class HenV2Storage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    counter: str
    fee: str
    manager: str
    metadata: dict[str, str]
    objkt: str
    swaps: dict[str, Swaps]
