# generated by DipDup 8.5.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class RegistryParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metadata: str
    subjkt: str
