# generated by DipDup 8.5.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class UnregistryParameter(BaseModel):
    pass
    model_config = ConfigDict(
        extra='forbid',
    )
